### ISSUE TITLE
General improvements to PyInstaller packaging setup

### ISSUE THREAD

**Issue by LewisGaul** [LewisGaul/minegauler#71]
- [x] Add README to root of packaged archive
- [x] Add symlink to executable in root of archive
- [x] Script more of the packaging process (in Python) - pyinstaller args, symlinks, zip/tar, cleanup
