### ISSUE TITLE
Highscore improvements

### ISSUE THREAD

**Issue by LewisGaul** [LewisGaul/minegauler#90]
Meta issue bringing together the planned highscore improvements.

### Bugs
- [ ] #72 Moving the highscores window with a filter menu open doesn't move the filter menu
- [ ] #84 Highlighted highscore row using smaller font on Windows

### High priority
- [ ] #80 Add option for fetching highscores
- [ ] #82 Local highscores view very slow with lots of entries
- [ ] #40 Save highscores to file with mouse tracking info
- [ ] #79 Store failed highscore uploads and retry later
- [ ] #63 Validate highscores being posted to remote DB

### Enhancements
- [ ] #85 Show settings corresponding to displayed highscores in highscore window
- [ ] #86 Update displayed highscores when a new one is set
- [ ] #87 Add compatibility layer for legacy highscores
- [ ] #88 Handle opening highscores window when a custom difficulty is in play
- [ ] #89 Add test coverage of highscores module
