### ISSUE TITLE
Window management issues

### ISSUE THREAD

**Issue by LewisGaul** [LewisGaul/minegauler#94]
Meta issue bringing together the issues involving window management/sizing.

- [ ] #49 Remaining refinements for scrollbars
- [ ] #69 Weird sizing of help windows
- [ ] #67 Increase max size of window
