### ISSUE TITLE
Add more GitHub actions

### ISSUE THREAD

**Issue by LewisGaul** [LewisGaul/minegauler#98]
- [x] Codecov excluding test code (for badge)
- [x] Tests on multiple platforms
- [x] Tests on multiple Python versions

**Comment by LewisGaul** [comment]
Testing on multiple platforms is non-trivial because of the need to set up a display (x-server on Linux).
