### ISSUE TITLE
Upcoming features

### ISSUE THREAD

**Issue by LewisGaul** [LewisGaul/minegauler#99]
Meta issue for tracking upcoming features.

### v4.0
- [ ] #58 Support maximising the main window (and persisting the state)
- [ ] #80 Add option for fetching highscores

### v4.1
- [ ] #32 Add probabilities
- [ ] #33 Add cell number detection option
- [ ] #26 Add the option of having multiple lives
- [ ] #77 Add ability to customise marker/number images
- [ ] #34 Add pause option (with 'p')
- [ ] #35 Add ability to hide the timer with right-click
- [ ] #76 Add factory reset option

### v4.2
- [ ] #41 Add 'split cells' mode
- [ ] #83 Check for updates when starting up the app
- [ ] #79 Store failed highscore uploads and retry later
- [ ] #75 Add welcome pop-up when first opening the app
